version: "3.8"
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: app:EliteServe
    container_name: EliteCRM
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
